[package]
name = "file-expert"
version = "1.0.0-alpha.0"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"

[dependencies]
clap = "=3.0.0-beta.4"
lazy_static = "1.4.0"
fancy-regex = "0.6.0"
