[package]
name = "file-expert"
version = "0.1.0"
authors = ["Bahtiar `kalkin-` Gadimov <bahtiar@gadimov.de>"]
edition = "2018"
build = "build.rs"

[dependencies]
clap = "3.0.0-beta.2"
regex = "1"
walkdir = "2"

[build-dependencies]
walkdir = "2"
