#!/bin/bash
#  Copyright © 2019 Bahtiar `kalkin` Gadimov
#
#    This file is part of file-expert.
#
#  file-expert is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  file-expert is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with file-expert.  If not, see <https://www.gnu.org/licenses/>.

quit() {
    exit 1
}

trap quit SIGINT SIGTERM

SAMPLES=linguist/samples

check() {
    lang=$1
    git --git-dir=linguist/.git ls-files "samples/$lang" \
        |while read -r line; do echo "linguist/$line"; done |./file-expert \
        |while read -r line; do
            [ "$lang" = "Fstar" ] && lang="F*"
            [ "$lang" = "Java Properties" ] && lang="Java properties"
            result=$(echo "$line"|cut -f2)
            filename=$(echo "$line"|cut -f1)
            if [ "$result" = "$lang" ]; then
                printf '.' > /dev/stderr
            elif [ "$result" = "Unknown file" ]; then
                printf "?" > /dev/stderr
                echo "????: $result != $lang"$'\t'"$filename" >> ./test-results
                echo "???"
            else
                printf "F" > /dev/stderr
                echo "FAIL: $result != $lang"$'\t'"$filename" >> ./test-results
                echo "FAIL"
            fi
        done;
}

rm -f ./test-results
for smth in "$SAMPLES"/*; do
    if [ -d "$smth" ]; then
        check "$(basename "$smth")"
    fi
done|cut -d: -f1|sort|uniq -c
