#!/bin/bash

quit() {
    exit 1
}

trap quit SIGINT SIGTERM

SAMPLES=linguist/samples

check() {
    lang=$1
    git --git-dir=linguist/.git ls-files "samples/$lang" \
        |while read -r line; do echo "linguist/$line"; done |./file-expert \
        |while read -r line; do
            result=$(echo "$line"|cut -f2)
            filename=$(echo "$line"|cut -f1)
            if [ "$result" = "$lang" ]; then
                echo "PASS"
            elif [ "$result" = "Unknown file" ]; then
                echo "????: $result != $lang"$'\t'"$filename" > /dev/stderr
                echo "???"
            else
                echo "FAIL: $result != $lang"$'\t'"$filename" > /dev/stderr
                echo "FAIL"
            fi
        done;
}

for smth in "$SAMPLES"/*; do
    if [ -d "$smth" ]; then
        check "$(basename "$smth")"
    fi
done|cut -d: -f1|sort|uniq -c
