//
// Copyright (c) 2018-2020 Bahtiar `kalkin-` Gadimov.
//
// This file is part of file-expert
// (see https://github.com/kalkin/file-expert).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    pub static ref EXTENSIONS: HashMap<String, String> = [
        (".bsl".to_owned(), "1C Enterprise".to_owned()),
        (".os".to_owned(), "1C Enterprise".to_owned()),
        (".4dm".to_owned(), "4D".to_owned()),
        (".abap".to_owned(), "ABAP".to_owned()),
        (".asddls".to_owned(), "ABAP CDS".to_owned()),
        (".abnf".to_owned(), "ABNF".to_owned()),
        (".ash".to_owned(), "AGS Script".to_owned()),
        (".aidl".to_owned(), "AIDL".to_owned()),
        (".ampl".to_owned(), "AMPL".to_owned()),
        (".g4".to_owned(), "ANTLR".to_owned()),
        (".apib".to_owned(), "API Blueprint".to_owned()),
        (".apl".to_owned(), "APL".to_owned()),
        (".dyalog".to_owned(), "APL".to_owned()),
        (".asl".to_owned(), "ASL".to_owned()),
        (".dsl".to_owned(), "ASL".to_owned()),
        (".asn".to_owned(), "ASN.1".to_owned()),
        (".asn1".to_owned(), "ASN.1".to_owned()),
        (".asax".to_owned(), "ASP.NET".to_owned()),
        (".ascx".to_owned(), "ASP.NET".to_owned()),
        (".ashx".to_owned(), "ASP.NET".to_owned()),
        (".asmx".to_owned(), "ASP.NET".to_owned()),
        (".aspx".to_owned(), "ASP.NET".to_owned()),
        (".axd".to_owned(), "ASP.NET".to_owned()),
        (".dats".to_owned(), "ATS".to_owned()),
        (".hats".to_owned(), "ATS".to_owned()),
        (".sats".to_owned(), "ATS".to_owned()),
        (".adb".to_owned(), "Ada".to_owned()),
        (".ada".to_owned(), "Ada".to_owned()),
        (".ads".to_owned(), "Ada".to_owned()),
        (".afm".to_owned(), "Adobe Font Metrics".to_owned()),
        (".agda".to_owned(), "Agda".to_owned()),
        (".als".to_owned(), "Alloy".to_owned()),
        (".outjob".to_owned(), "Altium Designer".to_owned()),
        (".pcbdoc".to_owned(), "Altium Designer".to_owned()),
        (".prjpcb".to_owned(), "Altium Designer".to_owned()),
        (".schdoc".to_owned(), "Altium Designer".to_owned()),
        (".angelscript".to_owned(), "AngelScript".to_owned()),
        (".apacheconf".to_owned(), "ApacheConf".to_owned()),
        (".agc".to_owned(), "Apollo Guidance Computer".to_owned()),
        (".applescript".to_owned(), "AppleScript".to_owned()),
        (".scpt".to_owned(), "AppleScript".to_owned()),
        (".arc".to_owned(), "Arc".to_owned()),
        (".asciidoc".to_owned(), "AsciiDoc".to_owned()),
        (".adoc".to_owned(), "AsciiDoc".to_owned()),
        (".aj".to_owned(), "AspectJ".to_owned()),
        (".a51".to_owned(), "Assembly".to_owned()),
        (".nasm".to_owned(), "Assembly".to_owned()),
        (".astro".to_owned(), "Astro".to_owned()),
        (".aug".to_owned(), "Augeas".to_owned()),
        (".ahk".to_owned(), "AutoHotkey".to_owned()),
        (".ahkl".to_owned(), "AutoHotkey".to_owned()),
        (".au3".to_owned(), "AutoIt".to_owned()),
        (".avdl".to_owned(), "Avro IDL".to_owned()),
        (".awk".to_owned(), "Awk".to_owned()),
        (".auk".to_owned(), "Awk".to_owned()),
        (".gawk".to_owned(), "Awk".to_owned()),
        (".mawk".to_owned(), "Awk".to_owned()),
        (".nawk".to_owned(), "Awk".to_owned()),
        (".bal".to_owned(), "Ballerina".to_owned()),
        (".bat".to_owned(), "Batchfile".to_owned()),
        (".cmd".to_owned(), "Batchfile".to_owned()),
        (".befunge".to_owned(), "Befunge".to_owned()),
        (".bib".to_owned(), "BibTeX".to_owned()),
        (".bibtex".to_owned(), "BibTeX".to_owned()),
        (".bicep".to_owned(), "Bicep".to_owned()),
        (".bison".to_owned(), "Bison".to_owned()),
        (".blade".to_owned(), "Blade".to_owned()),
        (".blade.php".to_owned(), "Blade".to_owned()),
        (".decls".to_owned(), "BlitzBasic".to_owned()),
        (".bmx".to_owned(), "BlitzMax".to_owned()),
        (".bsv".to_owned(), "Bluespec".to_owned()),
        (".boo".to_owned(), "Boo".to_owned()),
        (".bpl".to_owned(), "Boogie".to_owned()),
        (".brs".to_owned(), "Brightscript".to_owned()),
        (".c".to_owned(), "C".to_owned()),
        (".cats".to_owned(), "C".to_owned()),
        (".idc".to_owned(), "C".to_owned()),
        (".csx".to_owned(), "C#".to_owned()),
        (".linq".to_owned(), "C#".to_owned()),
        (".cpp".to_owned(), "C++".to_owned()),
        (".c++".to_owned(), "C++".to_owned()),
        (".cc".to_owned(), "C++".to_owned()),
        (".cxx".to_owned(), "C++".to_owned()),
        (".h++".to_owned(), "C++".to_owned()),
        (".hpp".to_owned(), "C++".to_owned()),
        (".hxx".to_owned(), "C++".to_owned()),
        (".inl".to_owned(), "C++".to_owned()),
        (".ino".to_owned(), "C++".to_owned()),
        (".ipp".to_owned(), "C++".to_owned()),
        (".ixx".to_owned(), "C++".to_owned()),
        (".tcc".to_owned(), "C++".to_owned()),
        (".tpp".to_owned(), "C++".to_owned()),
        (".c-objdump".to_owned(), "C-ObjDump".to_owned()),
        (".chs".to_owned(), "C2hs Haskell".to_owned()),
        (".cil".to_owned(), "CIL".to_owned()),
        (".clp".to_owned(), "CLIPS".to_owned()),
        (".cmake".to_owned(), "CMake".to_owned()),
        (".cmake.in".to_owned(), "CMake".to_owned()),
        (".cob".to_owned(), "COBOL".to_owned()),
        (".cbl".to_owned(), "COBOL".to_owned()),
        (".ccp".to_owned(), "COBOL".to_owned()),
        (".cobol".to_owned(), "COBOL".to_owned()),
        (".cpy".to_owned(), "COBOL".to_owned()),
        (".dae".to_owned(), "COLLADA".to_owned()),
        (".cson".to_owned(), "CSON".to_owned()),
        (".css".to_owned(), "CSS".to_owned()),
        (".csv".to_owned(), "CSV".to_owned()),
        (".cabal".to_owned(), "Cabal Config".to_owned()),
        (".capnp".to_owned(), "Cap'n Proto".to_owned()),
        (".mss".to_owned(), "CartoCSS".to_owned()),
        (".ceylon".to_owned(), "Ceylon".to_owned()),
        (".chpl".to_owned(), "Chapel".to_owned()),
        (".ck".to_owned(), "ChucK".to_owned()),
        (".cirru".to_owned(), "Cirru".to_owned()),
        (".clw".to_owned(), "Clarion".to_owned()),
        (".clar".to_owned(), "Clarity".to_owned()),
        (".asp".to_owned(), "Classic ASP".to_owned()),
        (".icl".to_owned(), "Clean".to_owned()),
        (".dcl".to_owned(), "Clean".to_owned()),
        (".click".to_owned(), "Click".to_owned()),
        (".clj".to_owned(), "Clojure".to_owned()),
        (".boot".to_owned(), "Clojure".to_owned()),
        (".cl2".to_owned(), "Clojure".to_owned()),
        (".cljc".to_owned(), "Clojure".to_owned()),
        (".cljs".to_owned(), "Clojure".to_owned()),
        (".cljs.hl".to_owned(), "Clojure".to_owned()),
        (".cljscm".to_owned(), "Clojure".to_owned()),
        (".cljx".to_owned(), "Clojure".to_owned()),
        (".hic".to_owned(), "Clojure".to_owned()),
        (".soy".to_owned(), "Closure Templates".to_owned()),
        (".conllu".to_owned(), "CoNLL-U".to_owned()),
        (".conll".to_owned(), "CoNLL-U".to_owned()),
        (".ql".to_owned(), "CodeQL".to_owned()),
        (".qll".to_owned(), "CodeQL".to_owned()),
        (".coffee".to_owned(), "CoffeeScript".to_owned()),
        ("._coffee".to_owned(), "CoffeeScript".to_owned()),
        (".cjsx".to_owned(), "CoffeeScript".to_owned()),
        (".iced".to_owned(), "CoffeeScript".to_owned()),
        (".cfm".to_owned(), "ColdFusion".to_owned()),
        (".cfml".to_owned(), "ColdFusion".to_owned()),
        (".cfc".to_owned(), "ColdFusion CFC".to_owned()),
        (".asd".to_owned(), "Common Lisp".to_owned()),
        (".ny".to_owned(), "Common Lisp".to_owned()),
        (".podsl".to_owned(), "Common Lisp".to_owned()),
        (".sexp".to_owned(), "Common Lisp".to_owned()),
        (".cwl".to_owned(), "Common Workflow Language".to_owned()),
        (".cps".to_owned(), "Component Pascal".to_owned()),
        (".coq".to_owned(), "Coq".to_owned()),
        (".cppobjdump".to_owned(), "Cpp-ObjDump".to_owned()),
        (".c++-objdump".to_owned(), "Cpp-ObjDump".to_owned()),
        (".c++objdump".to_owned(), "Cpp-ObjDump".to_owned()),
        (".cpp-objdump".to_owned(), "Cpp-ObjDump".to_owned()),
        (".cxx-objdump".to_owned(), "Cpp-ObjDump".to_owned()),
        (".creole".to_owned(), "Creole".to_owned()),
        (".cr".to_owned(), "Crystal".to_owned()),
        (".orc".to_owned(), "Csound".to_owned()),
        (".udo".to_owned(), "Csound".to_owned()),
        (".csd".to_owned(), "Csound Document".to_owned()),
        (".sco".to_owned(), "Csound Score".to_owned()),
        (".cu".to_owned(), "Cuda".to_owned()),
        (".cuh".to_owned(), "Cuda".to_owned()),
        (".curry".to_owned(), "Curry".to_owned()),
        (".cy".to_owned(), "Cycript".to_owned()),
        (".pyx".to_owned(), "Cython".to_owned()),
        (".pxd".to_owned(), "Cython".to_owned()),
        (".pxi".to_owned(), "Cython".to_owned()),
        (".di".to_owned(), "D".to_owned()),
        (".d-objdump".to_owned(), "D-ObjDump".to_owned()),
        (".com".to_owned(), "DIGITAL Command Language".to_owned()),
        (".dm".to_owned(), "DM".to_owned()),
        (".zone".to_owned(), "DNS Zone".to_owned()),
        (".arpa".to_owned(), "DNS Zone".to_owned()),
        (".dfy".to_owned(), "Dafny".to_owned()),
        (".darcspatch".to_owned(), "Darcs Patch".to_owned()),
        (".dpatch".to_owned(), "Darcs Patch".to_owned()),
        (".dart".to_owned(), "Dart".to_owned()),
        (".dwl".to_owned(), "DataWeave".to_owned()),
        (".dhall".to_owned(), "Dhall".to_owned()),
        (".diff".to_owned(), "Diff".to_owned()),
        (".patch".to_owned(), "Diff".to_owned()),
        (".dockerfile".to_owned(), "Dockerfile".to_owned()),
        (".djs".to_owned(), "Dogescript".to_owned()),
        (".dylan".to_owned(), "Dylan".to_owned()),
        (".dyl".to_owned(), "Dylan".to_owned()),
        (".intr".to_owned(), "Dylan".to_owned()),
        (".lid".to_owned(), "Dylan".to_owned()),
        (".e".to_owned(), "E".to_owned()),
        (".eml".to_owned(), "E-mail".to_owned()),
        (".mbox".to_owned(), "E-mail".to_owned()),
        (".ebnf".to_owned(), "EBNF".to_owned()),
        (".eclxml".to_owned(), "ECL".to_owned()),
        (".ejs".to_owned(), "EJS".to_owned()),
        (".ect".to_owned(), "EJS".to_owned()),
        (".ejs.t".to_owned(), "EJS".to_owned()),
        (".jst".to_owned(), "EJS".to_owned()),
        (".eq".to_owned(), "EQ".to_owned()),
        (".eb".to_owned(), "Easybuild".to_owned()),
        (".epj".to_owned(), "Ecere Projects".to_owned()),
        (".edc".to_owned(), "Edje Data Collection".to_owned()),
        (".e".to_owned(), "Eiffel".to_owned()),
        (".ex".to_owned(), "Elixir".to_owned()),
        (".exs".to_owned(), "Elixir".to_owned()),
        (".elm".to_owned(), "Elm".to_owned()),
        (".el".to_owned(), "Emacs Lisp".to_owned()),
        (".emacs".to_owned(), "Emacs Lisp".to_owned()),
        (".emacs.desktop".to_owned(), "Emacs Lisp".to_owned()),
        (".em".to_owned(), "EmberScript".to_owned()),
        (".emberscript".to_owned(), "EmberScript".to_owned()),
        (".erl".to_owned(), "Erlang".to_owned()),
        (".app.src".to_owned(), "Erlang".to_owned()),
        (".escript".to_owned(), "Erlang".to_owned()),
        (".hrl".to_owned(), "Erlang".to_owned()),
        (".xrl".to_owned(), "Erlang".to_owned()),
        (".yrl".to_owned(), "Erlang".to_owned()),
        (".fsi".to_owned(), "F#".to_owned()),
        (".fsx".to_owned(), "F#".to_owned()),
        (".fst".to_owned(), "F*".to_owned()),
        (".flf".to_owned(), "FIGlet Font".to_owned()),
        (".flux".to_owned(), "FLUX".to_owned()),
        (".factor".to_owned(), "Factor".to_owned()),
        (".fy".to_owned(), "Fancy".to_owned()),
        (".fancypack".to_owned(), "Fancy".to_owned()),
        (".fan".to_owned(), "Fantom".to_owned()),
        (".fnl".to_owned(), "Fennel".to_owned()),
        (".eam.fs".to_owned(), "Formatted".to_owned()),
        (".fth".to_owned(), "Forth".to_owned()),
        (".4th".to_owned(), "Forth".to_owned()),
        (".forth".to_owned(), "Forth".to_owned()),
        (".frt".to_owned(), "Forth".to_owned()),
        (".f77".to_owned(), "Fortran".to_owned()),
        (".fpp".to_owned(), "Fortran".to_owned()),
        (".f90".to_owned(), "Fortran Free Form".to_owned()),
        (".f03".to_owned(), "Fortran Free Form".to_owned()),
        (".f08".to_owned(), "Fortran Free Form".to_owned()),
        (".f95".to_owned(), "Fortran Free Form".to_owned()),
        (".bi".to_owned(), "FreeBasic".to_owned()),
        (".fut".to_owned(), "Futhark".to_owned()),
        (".cnc".to_owned(), "G-code".to_owned()),
        (".gco".to_owned(), "G-code".to_owned()),
        (".gcode".to_owned(), "G-code".to_owned()),
        (".gaml".to_owned(), "GAML".to_owned()),
        (".gms".to_owned(), "GAMS".to_owned()),
        (".gap".to_owned(), "GAP".to_owned()),
        (".gi".to_owned(), "GAP".to_owned()),
        (".gdb".to_owned(), "GDB".to_owned()),
        (".gdbinit".to_owned(), "GDB".to_owned()),
        (".ged".to_owned(), "GEDCOM".to_owned()),
        (".glsl".to_owned(), "GLSL".to_owned()),
        (".fp".to_owned(), "GLSL".to_owned()),
        (".frg".to_owned(), "GLSL".to_owned()),
        (".fsh".to_owned(), "GLSL".to_owned()),
        (".fshader".to_owned(), "GLSL".to_owned()),
        (".geo".to_owned(), "GLSL".to_owned()),
        (".geom".to_owned(), "GLSL".to_owned()),
        (".glslf".to_owned(), "GLSL".to_owned()),
        (".glslv".to_owned(), "GLSL".to_owned()),
        (".gshader".to_owned(), "GLSL".to_owned()),
        (".rchit".to_owned(), "GLSL".to_owned()),
        (".rmiss".to_owned(), "GLSL".to_owned()),
        (".tesc".to_owned(), "GLSL".to_owned()),
        (".tese".to_owned(), "GLSL".to_owned()),
        (".vert".to_owned(), "GLSL".to_owned()),
        (".vrx".to_owned(), "GLSL".to_owned()),
        (".vsh".to_owned(), "GLSL".to_owned()),
        (".vshader".to_owned(), "GLSL".to_owned()),
        (".gn".to_owned(), "GN".to_owned()),
        (".gni".to_owned(), "GN".to_owned()),
        (".gsc".to_owned(), "GSC".to_owned()),
        (".csc".to_owned(), "GSC".to_owned()),
        (".gsh".to_owned(), "GSC".to_owned()),
        (".kid".to_owned(), "Genshi".to_owned()),
        (".ebuild".to_owned(), "Gentoo Ebuild".to_owned()),
        (".eclass".to_owned(), "Gentoo Eclass".to_owned()),
        (".gbr".to_owned(), "Gerber Image".to_owned()),
        (".cmp".to_owned(), "Gerber Image".to_owned()),
        (".gbl".to_owned(), "Gerber Image".to_owned()),
        (".gbo".to_owned(), "Gerber Image".to_owned()),
        (".gbp".to_owned(), "Gerber Image".to_owned()),
        (".gbs".to_owned(), "Gerber Image".to_owned()),
        (".gko".to_owned(), "Gerber Image".to_owned()),
        (".gpb".to_owned(), "Gerber Image".to_owned()),
        (".gpt".to_owned(), "Gerber Image".to_owned()),
        (".gtl".to_owned(), "Gerber Image".to_owned()),
        (".gto".to_owned(), "Gerber Image".to_owned()),
        (".gtp".to_owned(), "Gerber Image".to_owned()),
        (".gts".to_owned(), "Gerber Image".to_owned()),
        (".po".to_owned(), "Gettext Catalog".to_owned()),
        (".pot".to_owned(), "Gettext Catalog".to_owned()),
        (".feature".to_owned(), "Gherkin".to_owned()),
        (".story".to_owned(), "Gherkin".to_owned()),
        (".gitconfig".to_owned(), "Git Config".to_owned()),
        (".gleam".to_owned(), "Gleam".to_owned()),
        (".glf".to_owned(), "Glyph".to_owned()),
        (
            ".bdf".to_owned(),
            "Glyph Bitmap Distribution Format".to_owned()
        ),
        (".gpr".to_owned(), "GNAT Project Manager".to_owned()),
        (".gp".to_owned(), "Gnuplot".to_owned()),
        (".gnu".to_owned(), "Gnuplot".to_owned()),
        (".gnuplot".to_owned(), "Gnuplot".to_owned()),
        (".plot".to_owned(), "Gnuplot".to_owned()),
        (".plt".to_owned(), "Gnuplot".to_owned()),
        (".go".to_owned(), "Go".to_owned()),
        (".golo".to_owned(), "Golo".to_owned()),
        (".gsx".to_owned(), "Gosu".to_owned()),
        (".vark".to_owned(), "Gosu".to_owned()),
        (".grace".to_owned(), "Grace".to_owned()),
        (".gradle".to_owned(), "Gradle".to_owned()),
        (".gf".to_owned(), "Grammatical Framework".to_owned()),
        (".graphql".to_owned(), "GraphQL".to_owned()),
        (".gql".to_owned(), "GraphQL".to_owned()),
        (".graphqls".to_owned(), "GraphQL".to_owned()),
        (".dot".to_owned(), "Graphviz (DOT)".to_owned()),
        (".gv".to_owned(), "Graphviz (DOT)".to_owned()),
        (".groovy".to_owned(), "Groovy".to_owned()),
        (".grt".to_owned(), "Groovy".to_owned()),
        (".gtpl".to_owned(), "Groovy".to_owned()),
        (".gvy".to_owned(), "Groovy".to_owned()),
        (".gsp".to_owned(), "Groovy Server Pages".to_owned()),
        (".hcl".to_owned(), "HCL".to_owned()),
        (".nomad".to_owned(), "HCL".to_owned()),
        (".tf".to_owned(), "HCL".to_owned()),
        (".tfvars".to_owned(), "HCL".to_owned()),
        (".hlsl".to_owned(), "HLSL".to_owned()),
        (".cginc".to_owned(), "HLSL".to_owned()),
        (".fxh".to_owned(), "HLSL".to_owned()),
        (".hlsli".to_owned(), "HLSL".to_owned()),
        (".html".to_owned(), "HTML".to_owned()),
        (".hta".to_owned(), "HTML".to_owned()),
        (".htm".to_owned(), "HTML".to_owned()),
        (".html.hl".to_owned(), "HTML".to_owned()),
        (".xht".to_owned(), "HTML".to_owned()),
        (".xhtml".to_owned(), "HTML".to_owned()),
        (".ecr".to_owned(), "HTML+ECR".to_owned()),
        (".eex".to_owned(), "HTML+EEX".to_owned()),
        (".html.heex".to_owned(), "HTML+EEX".to_owned()),
        (".html.leex".to_owned(), "HTML+EEX".to_owned()),
        (".erb".to_owned(), "HTML+ERB".to_owned()),
        (".erb.deface".to_owned(), "HTML+ERB".to_owned()),
        (".rhtml".to_owned(), "HTML+ERB".to_owned()),
        (".phtml".to_owned(), "HTML+PHP".to_owned()),
        (".cshtml".to_owned(), "HTML+Razor".to_owned()),
        (".razor".to_owned(), "HTML+Razor".to_owned()),
        (".http".to_owned(), "HTTP".to_owned()),
        (".hxml".to_owned(), "HXML".to_owned()),
        (".hack".to_owned(), "Hack".to_owned()),
        (".hhi".to_owned(), "Hack".to_owned()),
        (".haml".to_owned(), "Haml".to_owned()),
        (".haml.deface".to_owned(), "Haml".to_owned()),
        (".handlebars".to_owned(), "Handlebars".to_owned()),
        (".hbs".to_owned(), "Handlebars".to_owned()),
        (".hb".to_owned(), "Harbour".to_owned()),
        (".hs".to_owned(), "Haskell".to_owned()),
        (".hs-boot".to_owned(), "Haskell".to_owned()),
        (".hsc".to_owned(), "Haskell".to_owned()),
        (".hx".to_owned(), "Haxe".to_owned()),
        (".hxsl".to_owned(), "Haxe".to_owned()),
        (".hql".to_owned(), "HiveQL".to_owned()),
        (".hc".to_owned(), "HolyC".to_owned()),
        (".hy".to_owned(), "Hy".to_owned()),
        (".dlm".to_owned(), "IDL".to_owned()),
        (".ipf".to_owned(), "IGOR Pro".to_owned()),
        (".ini".to_owned(), "INI".to_owned()),
        (".dof".to_owned(), "INI".to_owned()),
        (".lektorproject".to_owned(), "INI".to_owned()),
        (".prefs".to_owned(), "INI".to_owned()),
        (".irclog".to_owned(), "IRC log".to_owned()),
        (".weechatlog".to_owned(), "IRC log".to_owned()),
        (".idr".to_owned(), "Idris".to_owned()),
        (".lidr".to_owned(), "Idris".to_owned()),
        (".gitignore".to_owned(), "Ignore List".to_owned()),
        (".ijm".to_owned(), "ImageJ Macro".to_owned()),
        (".ni".to_owned(), "Inform 7".to_owned()),
        (".i7x".to_owned(), "Inform 7".to_owned()),
        (".iss".to_owned(), "Inno Setup".to_owned()),
        (".isl".to_owned(), "Inno Setup".to_owned()),
        (".io".to_owned(), "Io".to_owned()),
        (".ik".to_owned(), "Ioke".to_owned()),
        (".thy".to_owned(), "Isabelle".to_owned()),
        (".ijs".to_owned(), "J".to_owned()),
        (".flex".to_owned(), "JFlex".to_owned()),
        (".jflex".to_owned(), "JFlex".to_owned()),
        (".json".to_owned(), "JSON".to_owned()),
        (".avsc".to_owned(), "JSON".to_owned()),
        (".geojson".to_owned(), "JSON".to_owned()),
        (".gltf".to_owned(), "JSON".to_owned()),
        (".har".to_owned(), "JSON".to_owned()),
        (".json-tmlanguage".to_owned(), "JSON".to_owned()),
        (".jsonl".to_owned(), "JSON".to_owned()),
        (".mcmeta".to_owned(), "JSON".to_owned()),
        (".tfstate".to_owned(), "JSON".to_owned()),
        (".tfstate.backup".to_owned(), "JSON".to_owned()),
        (".topojson".to_owned(), "JSON".to_owned()),
        (".webapp".to_owned(), "JSON".to_owned()),
        (".webmanifest".to_owned(), "JSON".to_owned()),
        (".yyp".to_owned(), "JSON".to_owned()),
        (".jsonc".to_owned(), "JSON with Comments".to_owned()),
        (".sublime-build".to_owned(), "JSON with Comments".to_owned()),
        (
            ".sublime-commands".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime-completions".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime-keymap".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (".sublime-macro".to_owned(), "JSON with Comments".to_owned()),
        (".sublime-menu".to_owned(), "JSON with Comments".to_owned()),
        (
            ".sublime-mousemap".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime-project".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime-settings".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (".sublime-theme".to_owned(), "JSON with Comments".to_owned()),
        (
            ".sublime-workspace".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime_metrics".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            ".sublime_session".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (".json5".to_owned(), "JSON5".to_owned()),
        (".jsonld".to_owned(), "JSONLD".to_owned()),
        (".janet".to_owned(), "Janet".to_owned()),
        (".java".to_owned(), "Java".to_owned()),
        (".jav".to_owned(), "Java".to_owned()),
        (".jsp".to_owned(), "Java Server Pages".to_owned()),
        (".js".to_owned(), "JavaScript".to_owned()),
        ("._js".to_owned(), "JavaScript".to_owned()),
        (".bones".to_owned(), "JavaScript".to_owned()),
        (".cjs".to_owned(), "JavaScript".to_owned()),
        (".es6".to_owned(), "JavaScript".to_owned()),
        (".jake".to_owned(), "JavaScript".to_owned()),
        (".javascript".to_owned(), "JavaScript".to_owned()),
        (".jsb".to_owned(), "JavaScript".to_owned()),
        (".jscad".to_owned(), "JavaScript".to_owned()),
        (".jsfl".to_owned(), "JavaScript".to_owned()),
        (".jsm".to_owned(), "JavaScript".to_owned()),
        (".jss".to_owned(), "JavaScript".to_owned()),
        (".jsx".to_owned(), "JavaScript".to_owned()),
        (".mjs".to_owned(), "JavaScript".to_owned()),
        (".njs".to_owned(), "JavaScript".to_owned()),
        (".pac".to_owned(), "JavaScript".to_owned()),
        (".sjs".to_owned(), "JavaScript".to_owned()),
        (".ssjs".to_owned(), "JavaScript".to_owned()),
        (".xsjs".to_owned(), "JavaScript".to_owned()),
        (".xsjslib".to_owned(), "JavaScript".to_owned()),
        (".js.erb".to_owned(), "JavaScript+ERB".to_owned()),
        (".snap".to_owned(), "Jest Snapshot".to_owned()),
        (".jinja".to_owned(), "Jinja".to_owned()),
        (".j2".to_owned(), "Jinja".to_owned()),
        (".jinja2".to_owned(), "Jinja".to_owned()),
        (".jison".to_owned(), "Jison".to_owned()),
        (".jisonlex".to_owned(), "Jison Lex".to_owned()),
        (".ol".to_owned(), "Jolie".to_owned()),
        (".iol".to_owned(), "Jolie".to_owned()),
        (".jsonnet".to_owned(), "Jsonnet".to_owned()),
        (".libsonnet".to_owned(), "Jsonnet".to_owned()),
        (".jl".to_owned(), "Julia".to_owned()),
        (".ipynb".to_owned(), "Jupyter Notebook".to_owned()),
        (".krl".to_owned(), "KRL".to_owned()),
        (".ksy".to_owned(), "Kaitai Struct".to_owned()),
        (".kak".to_owned(), "KakouneScript".to_owned()),
        (".kicad_pcb".to_owned(), "KiCad Layout".to_owned()),
        (".kicad_mod".to_owned(), "KiCad Layout".to_owned()),
        (".kicad_wks".to_owned(), "KiCad Layout".to_owned()),
        (".kit".to_owned(), "Kit".to_owned()),
        (".kt".to_owned(), "Kotlin".to_owned()),
        (".ktm".to_owned(), "Kotlin".to_owned()),
        (".kts".to_owned(), "Kotlin".to_owned()),
        (".lfe".to_owned(), "LFE".to_owned()),
        (".ll".to_owned(), "LLVM".to_owned()),
        (".lol".to_owned(), "LOLCODE".to_owned()),
        (".lsl".to_owned(), "LSL".to_owned()),
        (".lslp".to_owned(), "LSL".to_owned()),
        (".lvproj".to_owned(), "LabVIEW".to_owned()),
        (".lvlib".to_owned(), "LabVIEW".to_owned()),
        (".lark".to_owned(), "Lark".to_owned()),
        (".lasso".to_owned(), "Lasso".to_owned()),
        (".las".to_owned(), "Lasso".to_owned()),
        (".lasso8".to_owned(), "Lasso".to_owned()),
        (".lasso9".to_owned(), "Lasso".to_owned()),
        (".latte".to_owned(), "Latte".to_owned()),
        (".lean".to_owned(), "Lean".to_owned()),
        (".hlean".to_owned(), "Lean".to_owned()),
        (".less".to_owned(), "Less".to_owned()),
        (".lex".to_owned(), "Lex".to_owned()),
        (".ly".to_owned(), "LilyPond".to_owned()),
        (".ily".to_owned(), "LilyPond".to_owned()),
        (".ld".to_owned(), "Linker Script".to_owned()),
        (".lds".to_owned(), "Linker Script".to_owned()),
        (".liquid".to_owned(), "Liquid".to_owned()),
        (".lagda".to_owned(), "Literate Agda".to_owned()),
        (".litcoffee".to_owned(), "Literate CoffeeScript".to_owned()),
        (".coffee.md".to_owned(), "Literate CoffeeScript".to_owned()),
        (".lhs".to_owned(), "Literate Haskell".to_owned()),
        ("._ls".to_owned(), "LiveScript".to_owned()),
        (".xm".to_owned(), "Logos".to_owned()),
        (".xi".to_owned(), "Logos".to_owned()),
        (".lgt".to_owned(), "Logtalk".to_owned()),
        (".logtalk".to_owned(), "Logtalk".to_owned()),
        (".lookml".to_owned(), "LookML".to_owned()),
        (".model.lkml".to_owned(), "LookML".to_owned()),
        (".view.lkml".to_owned(), "LookML".to_owned()),
        (".lua".to_owned(), "Lua".to_owned()),
        (".nse".to_owned(), "Lua".to_owned()),
        (".p8".to_owned(), "Lua".to_owned()),
        (".pd_lua".to_owned(), "Lua".to_owned()),
        (".rbxs".to_owned(), "Lua".to_owned()),
        (".rockspec".to_owned(), "Lua".to_owned()),
        (".wlua".to_owned(), "Lua".to_owned()),
        (".mumps".to_owned(), "M".to_owned()),
        (".matlab".to_owned(), "MATLAB".to_owned()),
        (".mcr".to_owned(), "MAXScript".to_owned()),
        (".mlir".to_owned(), "MLIR".to_owned()),
        (".mq4".to_owned(), "MQL4".to_owned()),
        (".mq5".to_owned(), "MQL5".to_owned()),
        (".mqh".to_owned(), "MQL5".to_owned()),
        (".mtml".to_owned(), "MTML".to_owned()),
        (".muf".to_owned(), "MUF".to_owned()),
        (".m2".to_owned(), "Macaulay2".to_owned()),
        (".mak".to_owned(), "Makefile".to_owned()),
        (".make".to_owned(), "Makefile".to_owned()),
        (".makefile".to_owned(), "Makefile".to_owned()),
        (".mk".to_owned(), "Makefile".to_owned()),
        (".mkfile".to_owned(), "Makefile".to_owned()),
        (".mako".to_owned(), "Mako".to_owned()),
        (".mao".to_owned(), "Mako".to_owned()),
        (".markdown".to_owned(), "Markdown".to_owned()),
        (".mdown".to_owned(), "Markdown".to_owned()),
        (".mdwn".to_owned(), "Markdown".to_owned()),
        (".mdx".to_owned(), "Markdown".to_owned()),
        (".mkd".to_owned(), "Markdown".to_owned()),
        (".mkdn".to_owned(), "Markdown".to_owned()),
        (".mkdown".to_owned(), "Markdown".to_owned()),
        (".ronn".to_owned(), "Markdown".to_owned()),
        (".workbook".to_owned(), "Markdown".to_owned()),
        (".marko".to_owned(), "Marko".to_owned()),
        (".mathematica".to_owned(), "Mathematica".to_owned()),
        (".cdf".to_owned(), "Mathematica".to_owned()),
        (".ma".to_owned(), "Mathematica".to_owned()),
        (".mt".to_owned(), "Mathematica".to_owned()),
        (".nbp".to_owned(), "Mathematica".to_owned()),
        (".wl".to_owned(), "Mathematica".to_owned()),
        (".wlt".to_owned(), "Mathematica".to_owned()),
        (".maxpat".to_owned(), "Max".to_owned()),
        (".maxhelp".to_owned(), "Max".to_owned()),
        (".maxproj".to_owned(), "Max".to_owned()),
        (".mxt".to_owned(), "Max".to_owned()),
        (".pat".to_owned(), "Max".to_owned()),
        (".metal".to_owned(), "Metal".to_owned()),
        (
            ".sln".to_owned(),
            "Microsoft Visual Studio Solution".to_owned()
        ),
        (".minid".to_owned(), "MiniD".to_owned()),
        (".mint".to_owned(), "Mint".to_owned()),
        (".druby".to_owned(), "Mirah".to_owned()),
        (".duby".to_owned(), "Mirah".to_owned()),
        (".mirah".to_owned(), "Mirah".to_owned()),
        (".i3".to_owned(), "Modula-3".to_owned()),
        (".ig".to_owned(), "Modula-3".to_owned()),
        (".m3".to_owned(), "Modula-3".to_owned()),
        (".mg".to_owned(), "Modula-3".to_owned()),
        (".mms".to_owned(), "Module Management System".to_owned()),
        (".mmk".to_owned(), "Module Management System".to_owned()),
        (".monkey".to_owned(), "Monkey".to_owned()),
        (".monkey2".to_owned(), "Monkey".to_owned()),
        (".moon".to_owned(), "MoonScript".to_owned()),
        (".x68".to_owned(), "Motorola 68K Assembly".to_owned()),
        (".muse".to_owned(), "Muse".to_owned()),
        (".mustache".to_owned(), "Mustache".to_owned()),
        (".myt".to_owned(), "Myghty".to_owned()),
        (".nasl".to_owned(), "NASL".to_owned()),
        (".neon".to_owned(), "NEON".to_owned()),
        (".nsi".to_owned(), "NSIS".to_owned()),
        (".nsh".to_owned(), "NSIS".to_owned()),
        (".nss".to_owned(), "NWScript".to_owned()),
        (".ne".to_owned(), "Nearley".to_owned()),
        (".nearley".to_owned(), "Nearley".to_owned()),
        (".axs".to_owned(), "NetLinx".to_owned()),
        (".axi".to_owned(), "NetLinx".to_owned()),
        (".axs.erb".to_owned(), "NetLinx+ERB".to_owned()),
        (".axi.erb".to_owned(), "NetLinx+ERB".to_owned()),
        (".nlogo".to_owned(), "NetLogo".to_owned()),
        (".nf".to_owned(), "Nextflow".to_owned()),
        (".nginx".to_owned(), "Nginx".to_owned()),
        (".nginxconf".to_owned(), "Nginx".to_owned()),
        (".nim".to_owned(), "Nim".to_owned()),
        (".nim.cfg".to_owned(), "Nim".to_owned()),
        (".nimble".to_owned(), "Nim".to_owned()),
        (".nimrod".to_owned(), "Nim".to_owned()),
        (".nims".to_owned(), "Nim".to_owned()),
        (".ninja".to_owned(), "Ninja".to_owned()),
        (".nit".to_owned(), "Nit".to_owned()),
        (".nix".to_owned(), "Nix".to_owned()),
        (".nu".to_owned(), "Nu".to_owned()),
        (".numpy".to_owned(), "NumPy".to_owned()),
        (".numpyw".to_owned(), "NumPy".to_owned()),
        (".numsc".to_owned(), "NumPy".to_owned()),
        (".njk".to_owned(), "Nunjucks".to_owned()),
        (".eliom".to_owned(), "OCaml".to_owned()),
        (".eliomi".to_owned(), "OCaml".to_owned()),
        (".ml4".to_owned(), "OCaml".to_owned()),
        (".mli".to_owned(), "OCaml".to_owned()),
        (".mll".to_owned(), "OCaml".to_owned()),
        (".mly".to_owned(), "OCaml".to_owned()),
        (".objdump".to_owned(), "ObjDump".to_owned()),
        (".sj".to_owned(), "Objective-J".to_owned()),
        (".omgrofl".to_owned(), "Omgrofl".to_owned()),
        (".opa".to_owned(), "Opa".to_owned()),
        (".opal".to_owned(), "Opal".to_owned()),
        (".rego".to_owned(), "Open Policy Agent".to_owned()),
        (".opencl".to_owned(), "OpenCL".to_owned()),
        (".qasm".to_owned(), "OpenQASM".to_owned()),
        (".scad".to_owned(), "OpenSCAD".to_owned()),
        (".glyphs".to_owned(), "OpenStep Property List".to_owned()),
        (".fea".to_owned(), "OpenType Feature File".to_owned()),
        (".org".to_owned(), "Org".to_owned()),
        (".ox".to_owned(), "Ox".to_owned()),
        (".oxh".to_owned(), "Ox".to_owned()),
        (".oxo".to_owned(), "Ox".to_owned()),
        (".oxygene".to_owned(), "Oxygene".to_owned()),
        (".oz".to_owned(), "Oz".to_owned()),
        (".p4".to_owned(), "P4".to_owned()),
        (".pegjs".to_owned(), "PEG.js".to_owned()),
        (".aw".to_owned(), "PHP".to_owned()),
        (".ctp".to_owned(), "PHP".to_owned()),
        (".php3".to_owned(), "PHP".to_owned()),
        (".php4".to_owned(), "PHP".to_owned()),
        (".php5".to_owned(), "PHP".to_owned()),
        (".phps".to_owned(), "PHP".to_owned()),
        (".phpt".to_owned(), "PHP".to_owned()),
        (".pls".to_owned(), "PLSQL".to_owned()),
        (".bdy".to_owned(), "PLSQL".to_owned()),
        (".fnc".to_owned(), "PLSQL".to_owned()),
        (".pck".to_owned(), "PLSQL".to_owned()),
        (".pkb".to_owned(), "PLSQL".to_owned()),
        (".pks".to_owned(), "PLSQL".to_owned()),
        (".plb".to_owned(), "PLSQL".to_owned()),
        (".plsql".to_owned(), "PLSQL".to_owned()),
        (".spc".to_owned(), "PLSQL".to_owned()),
        (".tpb".to_owned(), "PLSQL".to_owned()),
        (".tps".to_owned(), "PLSQL".to_owned()),
        (".trg".to_owned(), "PLSQL".to_owned()),
        (".vw".to_owned(), "PLSQL".to_owned()),
        (".pgsql".to_owned(), "PLpgSQL".to_owned()),
        (".pov".to_owned(), "POV-Ray SDL".to_owned()),
        (".pan".to_owned(), "Pan".to_owned()),
        (".psc".to_owned(), "Papyrus".to_owned()),
        (".parrot".to_owned(), "Parrot".to_owned()),
        (".pasm".to_owned(), "Parrot Assembly".to_owned()),
        (
            ".pir".to_owned(),
            "Parrot Internal Representation".to_owned()
        ),
        (".pas".to_owned(), "Pascal".to_owned()),
        (".dfm".to_owned(), "Pascal".to_owned()),
        (".dpr".to_owned(), "Pascal".to_owned()),
        (".lpr".to_owned(), "Pascal".to_owned()),
        (".pascal".to_owned(), "Pascal".to_owned()),
        (".pwn".to_owned(), "Pawn".to_owned()),
        (".sma".to_owned(), "Pawn".to_owned()),
        (".pep".to_owned(), "Pep8".to_owned()),
        (".perl".to_owned(), "Perl".to_owned()),
        (".ph".to_owned(), "Perl".to_owned()),
        (".plx".to_owned(), "Perl".to_owned()),
        (".psgi".to_owned(), "Perl".to_owned()),
        (".pic".to_owned(), "Pic".to_owned()),
        (".chem".to_owned(), "Pic".to_owned()),
        (".pkl".to_owned(), "Pickle".to_owned()),
        (".pig".to_owned(), "PigLatin".to_owned()),
        (".pike".to_owned(), "Pike".to_owned()),
        (".pmod".to_owned(), "Pike".to_owned()),
        (".puml".to_owned(), "PlantUML".to_owned()),
        (".iuml".to_owned(), "PlantUML".to_owned()),
        (".plantuml".to_owned(), "PlantUML".to_owned()),
        (".pod6".to_owned(), "Pod 6".to_owned()),
        (".pogo".to_owned(), "PogoScript".to_owned()),
        (".pony".to_owned(), "Pony".to_owned()),
        (".pcss".to_owned(), "PostCSS".to_owned()),
        (".postcss".to_owned(), "PostCSS".to_owned()),
        (".ps".to_owned(), "PostScript".to_owned()),
        (".eps".to_owned(), "PostScript".to_owned()),
        (".epsi".to_owned(), "PostScript".to_owned()),
        (".pfa".to_owned(), "PostScript".to_owned()),
        (".pbt".to_owned(), "PowerBuilder".to_owned()),
        (".sra".to_owned(), "PowerBuilder".to_owned()),
        (".sru".to_owned(), "PowerBuilder".to_owned()),
        (".srw".to_owned(), "PowerBuilder".to_owned()),
        (".ps1".to_owned(), "PowerShell".to_owned()),
        (".psd1".to_owned(), "PowerShell".to_owned()),
        (".psm1".to_owned(), "PowerShell".to_owned()),
        (".prisma".to_owned(), "Prisma".to_owned()),
        (".pde".to_owned(), "Processing".to_owned()),
        (".prolog".to_owned(), "Prolog".to_owned()),
        (".yap".to_owned(), "Prolog".to_owned()),
        (".pml".to_owned(), "Promela".to_owned()),
        (".spin".to_owned(), "Propeller Spin".to_owned()),
        (".proto".to_owned(), "Protocol Buffer".to_owned()),
        (
            ".textproto".to_owned(),
            "Protocol Buffer Text Format".to_owned()
        ),
        (
            ".pbtxt".to_owned(),
            "Protocol Buffer Text Format".to_owned()
        ),
        (".pub".to_owned(), "Public Key".to_owned()),
        (".jade".to_owned(), "Pug".to_owned()),
        (".pug".to_owned(), "Pug".to_owned()),
        (".pd".to_owned(), "Pure Data".to_owned()),
        (".pb".to_owned(), "PureBasic".to_owned()),
        (".pbi".to_owned(), "PureBasic".to_owned()),
        (".purs".to_owned(), "PureScript".to_owned()),
        (".py".to_owned(), "Python".to_owned()),
        (".gyp".to_owned(), "Python".to_owned()),
        (".gypi".to_owned(), "Python".to_owned()),
        (".lmi".to_owned(), "Python".to_owned()),
        (".py3".to_owned(), "Python".to_owned()),
        (".pyde".to_owned(), "Python".to_owned()),
        (".pyi".to_owned(), "Python".to_owned()),
        (".pyp".to_owned(), "Python".to_owned()),
        (".pyt".to_owned(), "Python".to_owned()),
        (".pyw".to_owned(), "Python".to_owned()),
        (".smk".to_owned(), "Python".to_owned()),
        (".tac".to_owned(), "Python".to_owned()),
        (".wsgi".to_owned(), "Python".to_owned()),
        (".xpy".to_owned(), "Python".to_owned()),
        (".pytb".to_owned(), "Python traceback".to_owned()),
        (".qml".to_owned(), "QML".to_owned()),
        (".qbs".to_owned(), "QML".to_owned()),
        (".pri".to_owned(), "QMake".to_owned()),
        (".rd".to_owned(), "R".to_owned()),
        (".rsx".to_owned(), "R".to_owned()),
        (".raml".to_owned(), "RAML".to_owned()),
        (".rdoc".to_owned(), "RDoc".to_owned()),
        (".rbbas".to_owned(), "REALbasic".to_owned()),
        (".rbfrm".to_owned(), "REALbasic".to_owned()),
        (".rbmnu".to_owned(), "REALbasic".to_owned()),
        (".rbres".to_owned(), "REALbasic".to_owned()),
        (".rbtbar".to_owned(), "REALbasic".to_owned()),
        (".rbuistate".to_owned(), "REALbasic".to_owned()),
        (".rexx".to_owned(), "REXX".to_owned()),
        (".pprx".to_owned(), "REXX".to_owned()),
        (".rex".to_owned(), "REXX".to_owned()),
        (".rmd".to_owned(), "RMarkdown".to_owned()),
        (".rpgle".to_owned(), "RPGLE".to_owned()),
        (".sqlrpgle".to_owned(), "RPGLE".to_owned()),
        (".rnh".to_owned(), "RUNOFF".to_owned()),
        (".rkt".to_owned(), "Racket".to_owned()),
        (".rktd".to_owned(), "Racket".to_owned()),
        (".rktl".to_owned(), "Racket".to_owned()),
        (".scrbl".to_owned(), "Racket".to_owned()),
        (".rl".to_owned(), "Ragel".to_owned()),
        (".6pl".to_owned(), "Raku".to_owned()),
        (".6pm".to_owned(), "Raku".to_owned()),
        (".nqp".to_owned(), "Raku".to_owned()),
        (".p6".to_owned(), "Raku".to_owned()),
        (".p6l".to_owned(), "Raku".to_owned()),
        (".p6m".to_owned(), "Raku".to_owned()),
        (".pl6".to_owned(), "Raku".to_owned()),
        (".pm6".to_owned(), "Raku".to_owned()),
        (".raku".to_owned(), "Raku".to_owned()),
        (".rakumod".to_owned(), "Raku".to_owned()),
        (".rsc".to_owned(), "Rascal".to_owned()),
        (".raw".to_owned(), "Raw token data".to_owned()),
        (".rei".to_owned(), "Reason".to_owned()),
        (".reb".to_owned(), "Rebol".to_owned()),
        (".r2".to_owned(), "Rebol".to_owned()),
        (".r3".to_owned(), "Rebol".to_owned()),
        (".rebol".to_owned(), "Rebol".to_owned()),
        (".red".to_owned(), "Red".to_owned()),
        (".reds".to_owned(), "Red".to_owned()),
        (".cw".to_owned(), "Redcode".to_owned()),
        (".regexp".to_owned(), "Regular Expression".to_owned()),
        (".regex".to_owned(), "Regular Expression".to_owned()),
        (".rsh".to_owned(), "RenderScript".to_owned()),
        (".rtf".to_owned(), "Rich Text Format".to_owned()),
        (".ring".to_owned(), "Ring".to_owned()),
        (".riot".to_owned(), "Riot".to_owned()),
        (".robot".to_owned(), "RobotFramework".to_owned()),
        (".roff".to_owned(), "Roff".to_owned()),
        (".me".to_owned(), "Roff".to_owned()),
        (".nr".to_owned(), "Roff".to_owned()),
        (".tmac".to_owned(), "Roff".to_owned()),
        (".rg".to_owned(), "Rouge".to_owned()),
        (".rb".to_owned(), "Ruby".to_owned()),
        (".builder".to_owned(), "Ruby".to_owned()),
        (".eye".to_owned(), "Ruby".to_owned()),
        (".gemspec".to_owned(), "Ruby".to_owned()),
        (".god".to_owned(), "Ruby".to_owned()),
        (".jbuilder".to_owned(), "Ruby".to_owned()),
        (".mspec".to_owned(), "Ruby".to_owned()),
        (".podspec".to_owned(), "Ruby".to_owned()),
        (".prawn".to_owned(), "Ruby".to_owned()),
        (".rabl".to_owned(), "Ruby".to_owned()),
        (".rake".to_owned(), "Ruby".to_owned()),
        (".rbi".to_owned(), "Ruby".to_owned()),
        (".rbuild".to_owned(), "Ruby".to_owned()),
        (".rbw".to_owned(), "Ruby".to_owned()),
        (".rbx".to_owned(), "Ruby".to_owned()),
        (".ru".to_owned(), "Ruby".to_owned()),
        (".ruby".to_owned(), "Ruby".to_owned()),
        (".thor".to_owned(), "Ruby".to_owned()),
        (".watchr".to_owned(), "Ruby".to_owned()),
        (".rs.in".to_owned(), "Rust".to_owned()),
        (".sas".to_owned(), "SAS".to_owned()),
        (".scss".to_owned(), "SCSS".to_owned()),
        (".te".to_owned(), "SELinux Policy".to_owned()),
        (".smt2".to_owned(), "SMT".to_owned()),
        (".smt".to_owned(), "SMT".to_owned()),
        (".sparql".to_owned(), "SPARQL".to_owned()),
        (".rq".to_owned(), "SPARQL".to_owned()),
        (".sqf".to_owned(), "SQF".to_owned()),
        (".hqf".to_owned(), "SQF".to_owned()),
        (".cql".to_owned(), "SQL".to_owned()),
        (".mysql".to_owned(), "SQL".to_owned()),
        (".tab".to_owned(), "SQL".to_owned()),
        (".udf".to_owned(), "SQL".to_owned()),
        (".viw".to_owned(), "SQL".to_owned()),
        (".db2".to_owned(), "SQLPL".to_owned()),
        (".ston".to_owned(), "STON".to_owned()),
        (".svg".to_owned(), "SVG".to_owned()),
        (".sage".to_owned(), "Sage".to_owned()),
        (".sagews".to_owned(), "Sage".to_owned()),
        (".sass".to_owned(), "Sass".to_owned()),
        (".scala".to_owned(), "Scala".to_owned()),
        (".kojo".to_owned(), "Scala".to_owned()),
        (".sbt".to_owned(), "Scala".to_owned()),
        (".scaml".to_owned(), "Scaml".to_owned()),
        (".scm".to_owned(), "Scheme".to_owned()),
        (".sld".to_owned(), "Scheme".to_owned()),
        (".sps".to_owned(), "Scheme".to_owned()),
        (".ss".to_owned(), "Scheme".to_owned()),
        (".sci".to_owned(), "Scilab".to_owned()),
        (".sce".to_owned(), "Scilab".to_owned()),
        (".self".to_owned(), "Self".to_owned()),
        (".sh".to_owned(), "Shell".to_owned()),
        (".bash".to_owned(), "Shell".to_owned()),
        (".bats".to_owned(), "Shell".to_owned()),
        (".command".to_owned(), "Shell".to_owned()),
        (".env".to_owned(), "Shell".to_owned()),
        (".ksh".to_owned(), "Shell".to_owned()),
        (".sh.in".to_owned(), "Shell".to_owned()),
        (".tmux".to_owned(), "Shell".to_owned()),
        (".tool".to_owned(), "Shell".to_owned()),
        (".zsh".to_owned(), "Shell".to_owned()),
        (".zsh-theme".to_owned(), "Shell".to_owned()),
        (".sh-session".to_owned(), "ShellSession".to_owned()),
        (".shen".to_owned(), "Shen".to_owned()),
        (".sieve".to_owned(), "Sieve".to_owned()),
        (".sl".to_owned(), "Slash".to_owned()),
        (".slim".to_owned(), "Slim".to_owned()),
        (".cocci".to_owned(), "SmPL".to_owned()),
        (".smali".to_owned(), "Smali".to_owned()),
        (".tpl".to_owned(), "Smarty".to_owned()),
        (".sp".to_owned(), "SourcePawn".to_owned()),
        (".sfd".to_owned(), "Spline Font Database".to_owned()),
        (".nut".to_owned(), "Squirrel".to_owned()),
        (".stan".to_owned(), "Stan".to_owned()),
        (".fun".to_owned(), "Standard ML".to_owned()),
        (".sig".to_owned(), "Standard ML".to_owned()),
        (".sml".to_owned(), "Standard ML".to_owned()),
        (".bzl".to_owned(), "Starlark".to_owned()),
        (".do".to_owned(), "Stata".to_owned()),
        (".ado".to_owned(), "Stata".to_owned()),
        (".doh".to_owned(), "Stata".to_owned()),
        (".ihlp".to_owned(), "Stata".to_owned()),
        (".mata".to_owned(), "Stata".to_owned()),
        (".matah".to_owned(), "Stata".to_owned()),
        (".sthlp".to_owned(), "Stata".to_owned()),
        (".styl".to_owned(), "Stylus".to_owned()),
        (".sss".to_owned(), "SugarSS".to_owned()),
        (".svelte".to_owned(), "Svelte".to_owned()),
        (".swift".to_owned(), "Swift".to_owned()),
        (".sv".to_owned(), "SystemVerilog".to_owned()),
        (".svh".to_owned(), "SystemVerilog".to_owned()),
        (".vh".to_owned(), "SystemVerilog".to_owned()),
        (".8xp".to_owned(), "TI Program".to_owned()),
        (".8xk".to_owned(), "TI Program".to_owned()),
        (".8xk.txt".to_owned(), "TI Program".to_owned()),
        (".8xp.txt".to_owned(), "TI Program".to_owned()),
        (".tla".to_owned(), "TLA".to_owned()),
        (".toml".to_owned(), "TOML".to_owned()),
        (".tsv".to_owned(), "TSV".to_owned()),
        (".txl".to_owned(), "TXL".to_owned()),
        (".tcl".to_owned(), "Tcl".to_owned()),
        (".adp".to_owned(), "Tcl".to_owned()),
        (".tcl.in".to_owned(), "Tcl".to_owned()),
        (".tm".to_owned(), "Tcl".to_owned()),
        (".tcsh".to_owned(), "Tcsh".to_owned()),
        (".csh".to_owned(), "Tcsh".to_owned()),
        (".tex".to_owned(), "TeX".to_owned()),
        (".aux".to_owned(), "TeX".to_owned()),
        (".bbx".to_owned(), "TeX".to_owned()),
        (".cbx".to_owned(), "TeX".to_owned()),
        (".dtx".to_owned(), "TeX".to_owned()),
        (".ins".to_owned(), "TeX".to_owned()),
        (".lbx".to_owned(), "TeX".to_owned()),
        (".ltx".to_owned(), "TeX".to_owned()),
        (".mkii".to_owned(), "TeX".to_owned()),
        (".mkiv".to_owned(), "TeX".to_owned()),
        (".mkvi".to_owned(), "TeX".to_owned()),
        (".sty".to_owned(), "TeX".to_owned()),
        (".tea".to_owned(), "Tea".to_owned()),
        (".texinfo".to_owned(), "Texinfo".to_owned()),
        (".texi".to_owned(), "Texinfo".to_owned()),
        (".txi".to_owned(), "Texinfo".to_owned()),
        (".no".to_owned(), "Text".to_owned()),
        (".textile".to_owned(), "Textile".to_owned()),
        (".thrift".to_owned(), "Thrift".to_owned()),
        (".tu".to_owned(), "Turing".to_owned()),
        (".ttl".to_owned(), "Turtle".to_owned()),
        (".twig".to_owned(), "Twig".to_owned()),
        (".tl".to_owned(), "Type Language".to_owned()),
        (".upc".to_owned(), "Unified Parallel C".to_owned()),
        (".anim".to_owned(), "Unity3D Asset".to_owned()),
        (".asset".to_owned(), "Unity3D Asset".to_owned()),
        (".mat".to_owned(), "Unity3D Asset".to_owned()),
        (".meta".to_owned(), "Unity3D Asset".to_owned()),
        (".prefab".to_owned(), "Unity3D Asset".to_owned()),
        (".unity".to_owned(), "Unity3D Asset".to_owned()),
        (".uno".to_owned(), "Uno".to_owned()),
        (".uc".to_owned(), "UnrealScript".to_owned()),
        (".ur".to_owned(), "UrWeb".to_owned()),
        (".urs".to_owned(), "UrWeb".to_owned()),
        (".frm".to_owned(), "VBA".to_owned()),
        (".frx".to_owned(), "VBA".to_owned()),
        (".vbs".to_owned(), "VBScript".to_owned()),
        (".vcl".to_owned(), "VCL".to_owned()),
        (".vhdl".to_owned(), "VHDL".to_owned()),
        (".vhd".to_owned(), "VHDL".to_owned()),
        (".vhf".to_owned(), "VHDL".to_owned()),
        (".vhi".to_owned(), "VHDL".to_owned()),
        (".vho".to_owned(), "VHDL".to_owned()),
        (".vhs".to_owned(), "VHDL".to_owned()),
        (".vht".to_owned(), "VHDL".to_owned()),
        (".vhw".to_owned(), "VHDL".to_owned()),
        (".vala".to_owned(), "Vala".to_owned()),
        (".vapi".to_owned(), "Vala".to_owned()),
        (".vdf".to_owned(), "Valve Data Format".to_owned()),
        (".veo".to_owned(), "Verilog".to_owned()),
        (".vim".to_owned(), "Vim Script".to_owned()),
        (".vimrc".to_owned(), "Vim Script".to_owned()),
        (".vmb".to_owned(), "Vim Script".to_owned()),
        (".snip".to_owned(), "Vim Snippet".to_owned()),
        (".snippet".to_owned(), "Vim Snippet".to_owned()),
        (".snippets".to_owned(), "Vim Snippet".to_owned()),
        (".vb".to_owned(), "Visual Basic .NET".to_owned()),
        (".vbhtml".to_owned(), "Visual Basic .NET".to_owned()),
        (".volt".to_owned(), "Volt".to_owned()),
        (".vue".to_owned(), "Vue".to_owned()),
        (".mtl".to_owned(), "Wavefront Material".to_owned()),
        (".obj".to_owned(), "Wavefront Object".to_owned()),
        (".owl".to_owned(), "Web Ontology Language".to_owned()),
        (".wast".to_owned(), "WebAssembly".to_owned()),
        (".wat".to_owned(), "WebAssembly".to_owned()),
        (".webidl".to_owned(), "WebIDL".to_owned()),
        (".vtt".to_owned(), "WebVTT".to_owned()),
        (".mediawiki".to_owned(), "Wikitext".to_owned()),
        (".wiki".to_owned(), "Wikitext".to_owned()),
        (".wikitext".to_owned(), "Wikitext".to_owned()),
        (".reg".to_owned(), "Windows Registry Entries".to_owned()),
        (".wlk".to_owned(), "Wollok".to_owned()),
        (".xbm".to_owned(), "X BitMap".to_owned()),
        (".xpm".to_owned(), "X PixMap".to_owned()),
        (".x10".to_owned(), "X10".to_owned()),
        (".xc".to_owned(), "XC".to_owned()),
        (".xml".to_owned(), "XML".to_owned()),
        (".adml".to_owned(), "XML".to_owned()),
        (".admx".to_owned(), "XML".to_owned()),
        (".ant".to_owned(), "XML".to_owned()),
        (".axml".to_owned(), "XML".to_owned()),
        (".builds".to_owned(), "XML".to_owned()),
        (".ccproj".to_owned(), "XML".to_owned()),
        (".ccxml".to_owned(), "XML".to_owned()),
        (".clixml".to_owned(), "XML".to_owned()),
        (".cproject".to_owned(), "XML".to_owned()),
        (".cscfg".to_owned(), "XML".to_owned()),
        (".csdef".to_owned(), "XML".to_owned()),
        (".csproj".to_owned(), "XML".to_owned()),
        (".ct".to_owned(), "XML".to_owned()),
        (".depproj".to_owned(), "XML".to_owned()),
        (".dita".to_owned(), "XML".to_owned()),
        (".ditamap".to_owned(), "XML".to_owned()),
        (".ditaval".to_owned(), "XML".to_owned()),
        (".dll.config".to_owned(), "XML".to_owned()),
        (".dotsettings".to_owned(), "XML".to_owned()),
        (".filters".to_owned(), "XML".to_owned()),
        (".fsproj".to_owned(), "XML".to_owned()),
        (".fxml".to_owned(), "XML".to_owned()),
        (".glade".to_owned(), "XML".to_owned()),
        (".gmx".to_owned(), "XML".to_owned()),
        (".grxml".to_owned(), "XML".to_owned()),
        (".hzp".to_owned(), "XML".to_owned()),
        (".iml".to_owned(), "XML".to_owned()),
        (".ivy".to_owned(), "XML".to_owned()),
        (".jelly".to_owned(), "XML".to_owned()),
        (".jsproj".to_owned(), "XML".to_owned()),
        (".kml".to_owned(), "XML".to_owned()),
        (".launch".to_owned(), "XML".to_owned()),
        (".mdpolicy".to_owned(), "XML".to_owned()),
        (".mjml".to_owned(), "XML".to_owned()),
        (".mxml".to_owned(), "XML".to_owned()),
        (".natvis".to_owned(), "XML".to_owned()),
        (".ndproj".to_owned(), "XML".to_owned()),
        (".nproj".to_owned(), "XML".to_owned()),
        (".nuspec".to_owned(), "XML".to_owned()),
        (".odd".to_owned(), "XML".to_owned()),
        (".osm".to_owned(), "XML".to_owned()),
        (".pkgproj".to_owned(), "XML".to_owned()),
        (".proj".to_owned(), "XML".to_owned()),
        (".props".to_owned(), "XML".to_owned()),
        (".ps1xml".to_owned(), "XML".to_owned()),
        (".psc1".to_owned(), "XML".to_owned()),
        (".pt".to_owned(), "XML".to_owned()),
        (".rdf".to_owned(), "XML".to_owned()),
        (".resx".to_owned(), "XML".to_owned()),
        (".rss".to_owned(), "XML".to_owned()),
        (".scxml".to_owned(), "XML".to_owned()),
        (".sfproj".to_owned(), "XML".to_owned()),
        (".shproj".to_owned(), "XML".to_owned()),
        (".srdf".to_owned(), "XML".to_owned()),
        (".storyboard".to_owned(), "XML".to_owned()),
        (".sublime-snippet".to_owned(), "XML".to_owned()),
        (".targets".to_owned(), "XML".to_owned()),
        (".tml".to_owned(), "XML".to_owned()),
        (".ui".to_owned(), "XML".to_owned()),
        (".urdf".to_owned(), "XML".to_owned()),
        (".ux".to_owned(), "XML".to_owned()),
        (".vbproj".to_owned(), "XML".to_owned()),
        (".vcxproj".to_owned(), "XML".to_owned()),
        (".vsixmanifest".to_owned(), "XML".to_owned()),
        (".vssettings".to_owned(), "XML".to_owned()),
        (".vstemplate".to_owned(), "XML".to_owned()),
        (".vxml".to_owned(), "XML".to_owned()),
        (".wixproj".to_owned(), "XML".to_owned()),
        (".wsdl".to_owned(), "XML".to_owned()),
        (".wsf".to_owned(), "XML".to_owned()),
        (".wxi".to_owned(), "XML".to_owned()),
        (".wxl".to_owned(), "XML".to_owned()),
        (".wxs".to_owned(), "XML".to_owned()),
        (".x3d".to_owned(), "XML".to_owned()),
        (".xacro".to_owned(), "XML".to_owned()),
        (".xaml".to_owned(), "XML".to_owned()),
        (".xib".to_owned(), "XML".to_owned()),
        (".xlf".to_owned(), "XML".to_owned()),
        (".xliff".to_owned(), "XML".to_owned()),
        (".xmi".to_owned(), "XML".to_owned()),
        (".xml.dist".to_owned(), "XML".to_owned()),
        (".xmp".to_owned(), "XML".to_owned()),
        (".xproj".to_owned(), "XML".to_owned()),
        (".xsd".to_owned(), "XML".to_owned()),
        (".xspec".to_owned(), "XML".to_owned()),
        (".xul".to_owned(), "XML".to_owned()),
        (".zcml".to_owned(), "XML".to_owned()),
        (".sttheme".to_owned(), "XML Property List".to_owned()),
        (".tmcommand".to_owned(), "XML Property List".to_owned()),
        (".tmlanguage".to_owned(), "XML Property List".to_owned()),
        (".tmpreferences".to_owned(), "XML Property List".to_owned()),
        (".tmsnippet".to_owned(), "XML Property List".to_owned()),
        (".tmtheme".to_owned(), "XML Property List".to_owned()),
        (".xsp-config".to_owned(), "XPages".to_owned()),
        (".xsp.metadata".to_owned(), "XPages".to_owned()),
        (".xpl".to_owned(), "XProc".to_owned()),
        (".xproc".to_owned(), "XProc".to_owned()),
        (".xquery".to_owned(), "XQuery".to_owned()),
        (".xq".to_owned(), "XQuery".to_owned()),
        (".xql".to_owned(), "XQuery".to_owned()),
        (".xqm".to_owned(), "XQuery".to_owned()),
        (".xqy".to_owned(), "XQuery".to_owned()),
        (".xs".to_owned(), "XS".to_owned()),
        (".xslt".to_owned(), "XSLT".to_owned()),
        (".xsl".to_owned(), "XSLT".to_owned()),
        (".xojo_code".to_owned(), "Xojo".to_owned()),
        (".xojo_menu".to_owned(), "Xojo".to_owned()),
        (".xojo_report".to_owned(), "Xojo".to_owned()),
        (".xojo_script".to_owned(), "Xojo".to_owned()),
        (".xojo_toolbar".to_owned(), "Xojo".to_owned()),
        (".xojo_window".to_owned(), "Xojo".to_owned()),
        (".xsh".to_owned(), "Xonsh".to_owned()),
        (".xtend".to_owned(), "Xtend".to_owned()),
        (".yml".to_owned(), "YAML".to_owned()),
        (".mir".to_owned(), "YAML".to_owned()),
        (".reek".to_owned(), "YAML".to_owned()),
        (".rviz".to_owned(), "YAML".to_owned()),
        (".sublime-syntax".to_owned(), "YAML".to_owned()),
        (".syntax".to_owned(), "YAML".to_owned()),
        (".yaml".to_owned(), "YAML".to_owned()),
        (".yaml-tmlanguage".to_owned(), "YAML".to_owned()),
        (".yaml.sed".to_owned(), "YAML".to_owned()),
        (".yml.mysql".to_owned(), "YAML".to_owned()),
        (".yang".to_owned(), "YANG".to_owned()),
        (".yar".to_owned(), "YARA".to_owned()),
        (".yara".to_owned(), "YARA".to_owned()),
        (".yasnippet".to_owned(), "YASnippet".to_owned()),
        (".y".to_owned(), "Yacc".to_owned()),
        (".yacc".to_owned(), "Yacc".to_owned()),
        (".zap".to_owned(), "ZAP".to_owned()),
        (".xzap".to_owned(), "ZAP".to_owned()),
        (".zil".to_owned(), "ZIL".to_owned()),
        (".mud".to_owned(), "ZIL".to_owned()),
        (".zeek".to_owned(), "Zeek".to_owned()),
        (".bro".to_owned(), "Zeek".to_owned()),
        (".zs".to_owned(), "ZenScript".to_owned()),
        (".zep".to_owned(), "Zephir".to_owned()),
        (".zig".to_owned(), "Zig".to_owned()),
        (".zimpl".to_owned(), "Zimpl".to_owned()),
        (".zmpl".to_owned(), "Zimpl".to_owned()),
        (".zpl".to_owned(), "Zimpl".to_owned()),
        (".desktop".to_owned(), "desktop".to_owned()),
        (".desktop.in".to_owned(), "desktop".to_owned()),
        (".service".to_owned(), "desktop".to_owned()),
        (".dircolors".to_owned(), "dircolors".to_owned()),
        (".ec".to_owned(), "eC".to_owned()),
        (".eh".to_owned(), "eC".to_owned()),
        (".edn".to_owned(), "edn".to_owned()),
        (".fish".to_owned(), "fish".to_owned()),
        (".hoon".to_owned(), "hoon".to_owned()),
        (".mrc".to_owned(), "mIRC Script".to_owned()),
        (".mcfunction".to_owned(), "mcfunction".to_owned()),
        (".mu".to_owned(), "mupad".to_owned()),
        (".nanorc".to_owned(), "nanorc".to_owned()),
        (".nc".to_owned(), "nesC".to_owned()),
        (".ooc".to_owned(), "ooc".to_owned()),
        (".rst".to_owned(), "reStructuredText".to_owned()),
        (".rest".to_owned(), "reStructuredText".to_owned()),
        (".rest.txt".to_owned(), "reStructuredText".to_owned()),
        (".rst.txt".to_owned(), "reStructuredText".to_owned()),
        (".sed".to_owned(), "sed".to_owned()),
        (".wdl".to_owned(), "wdl".to_owned()),
        (".wisp".to_owned(), "wisp".to_owned()),
        (".prg".to_owned(), "xBase".to_owned()),
        (".prw".to_owned(), "xBase".to_owned()),
    ]
    .iter()
    .cloned()
    .collect();
}
