//
// Copyright (c) 2018-2020 Bahtiar `kalkin-` Gadimov.
//
// This file is part of file-expert
// (see https://github.com/kalkin/file-expert).
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    pub static ref FILENAMES: HashMap<String, String> = [
        ("APKBUILD".to_owned(), "Alpine Abuild".to_owned()),
        ("ant.xml".to_owned(), "Ant Build System".to_owned()),
        ("build.xml".to_owned(), "Ant Build System".to_owned()),
        (".htaccess".to_owned(), "ApacheConf".to_owned()),
        ("apache2.conf".to_owned(), "ApacheConf".to_owned()),
        ("httpd.conf".to_owned(), "ApacheConf".to_owned()),
        (".browserslistrc".to_owned(), "Browserslist".to_owned()),
        ("browserslist".to_owned(), "Browserslist".to_owned()),
        ("CMakeLists.txt".to_owned(), "CMake".to_owned()),
        ("CODEOWNERS".to_owned(), "CODEOWNERS".to_owned()),
        ("cabal.config".to_owned(), "Cabal Config".to_owned()),
        ("cabal.project".to_owned(), "Cabal Config".to_owned()),
        ("riemann.config".to_owned(), "Clojure".to_owned()),
        (
            "firestore.rules".to_owned(),
            "Cloud Firestore Security Rules".to_owned()
        ),
        ("Cakefile".to_owned(), "CoffeeScript".to_owned()),
        ("Containerfile".to_owned(), "Dockerfile".to_owned()),
        ("Dockerfile".to_owned(), "Dockerfile".to_owned()),
        ("Earthfile".to_owned(), "Earthly".to_owned()),
        (".editorconfig".to_owned(), "EditorConfig".to_owned()),
        ("mix.lock".to_owned(), "Elixir".to_owned()),
        (".abbrev_defs".to_owned(), "Emacs Lisp".to_owned()),
        (".emacs".to_owned(), "Emacs Lisp".to_owned()),
        (".emacs.desktop".to_owned(), "Emacs Lisp".to_owned()),
        (".gnus".to_owned(), "Emacs Lisp".to_owned()),
        (".spacemacs".to_owned(), "Emacs Lisp".to_owned()),
        (".viper".to_owned(), "Emacs Lisp".to_owned()),
        ("Cask".to_owned(), "Emacs Lisp".to_owned()),
        ("Project.ede".to_owned(), "Emacs Lisp".to_owned()),
        ("_emacs".to_owned(), "Emacs Lisp".to_owned()),
        ("abbrev_defs".to_owned(), "Emacs Lisp".to_owned()),
        ("Emakefile".to_owned(), "Erlang".to_owned()),
        ("rebar.config".to_owned(), "Erlang".to_owned()),
        ("rebar.config.lock".to_owned(), "Erlang".to_owned()),
        ("rebar.lock".to_owned(), "Erlang".to_owned()),
        (".factor-boot-rc".to_owned(), "Factor".to_owned()),
        (".factor-rc".to_owned(), "Factor".to_owned()),
        ("Fakefile".to_owned(), "Fancy".to_owned()),
        (".gn".to_owned(), "GN".to_owned()),
        ("Gemfile.lock".to_owned(), "Gemfile.lock".to_owned()),
        (".gitattributes".to_owned(), "Git Attributes".to_owned()),
        (".gitconfig".to_owned(), "Git Config".to_owned()),
        (".gitmodules".to_owned(), "Git Config".to_owned()),
        ("go.sum".to_owned(), "Go Checksums".to_owned()),
        ("go.mod".to_owned(), "Go Module".to_owned()),
        ("Jenkinsfile".to_owned(), "Groovy".to_owned()),
        ("haproxy.cfg".to_owned(), "HAProxy".to_owned()),
        (".flake8".to_owned(), "INI".to_owned()),
        ("buildozer.spec".to_owned(), "INI".to_owned()),
        (".atomignore".to_owned(), "Ignore List".to_owned()),
        (".babelignore".to_owned(), "Ignore List".to_owned()),
        (".bzrignore".to_owned(), "Ignore List".to_owned()),
        (".coffeelintignore".to_owned(), "Ignore List".to_owned()),
        (".cvsignore".to_owned(), "Ignore List".to_owned()),
        (".dockerignore".to_owned(), "Ignore List".to_owned()),
        (".eleventyignore".to_owned(), "Ignore List".to_owned()),
        (".eslintignore".to_owned(), "Ignore List".to_owned()),
        (".gitignore".to_owned(), "Ignore List".to_owned()),
        (".markdownlintignore".to_owned(), "Ignore List".to_owned()),
        (".nodemonignore".to_owned(), "Ignore List".to_owned()),
        (".npmignore".to_owned(), "Ignore List".to_owned()),
        (".prettierignore".to_owned(), "Ignore List".to_owned()),
        (".stylelintignore".to_owned(), "Ignore List".to_owned()),
        (".vscodeignore".to_owned(), "Ignore List".to_owned()),
        ("gitignore-global".to_owned(), "Ignore List".to_owned()),
        ("gitignore_global".to_owned(), "Ignore List".to_owned()),
        ("ROOT".to_owned(), "Isabelle ROOT".to_owned()),
        ("MANIFEST.MF".to_owned(), "JAR Manifest".to_owned()),
        (".arcconfig".to_owned(), "JSON".to_owned()),
        (".auto-changelog".to_owned(), "JSON".to_owned()),
        (".c8rc".to_owned(), "JSON".to_owned()),
        (".htmlhintrc".to_owned(), "JSON".to_owned()),
        (".imgbotconfig".to_owned(), "JSON".to_owned()),
        (".nycrc".to_owned(), "JSON".to_owned()),
        (".tern-config".to_owned(), "JSON".to_owned()),
        (".tern-project".to_owned(), "JSON".to_owned()),
        (".watchmanconfig".to_owned(), "JSON".to_owned()),
        ("Pipfile.lock".to_owned(), "JSON".to_owned()),
        ("composer.lock".to_owned(), "JSON".to_owned()),
        ("mcmod.info".to_owned(), "JSON".to_owned()),
        (".babelrc".to_owned(), "JSON with Comments".to_owned()),
        (".eslintrc.json".to_owned(), "JSON with Comments".to_owned()),
        (".jscsrc".to_owned(), "JSON with Comments".to_owned()),
        (".jshintrc".to_owned(), "JSON with Comments".to_owned()),
        (".jslintrc".to_owned(), "JSON with Comments".to_owned()),
        (
            "api-extractor.json".to_owned(),
            "JSON with Comments".to_owned()
        ),
        (
            "devcontainer.json".to_owned(),
            "JSON with Comments".to_owned()
        ),
        ("jsconfig.json".to_owned(), "JSON with Comments".to_owned()),
        (
            "language-configuration.json".to_owned(),
            "JSON with Comments".to_owned()
        ),
        ("tsconfig.json".to_owned(), "JSON with Comments".to_owned()),
        ("tslint.json".to_owned(), "JSON with Comments".to_owned()),
        ("Jakefile".to_owned(), "JavaScript".to_owned()),
        ("Notebook".to_owned(), "Jupyter Notebook".to_owned()),
        ("kakrc".to_owned(), "KakouneScript".to_owned()),
        ("fp-lib-table".to_owned(), "KiCad Layout".to_owned()),
        ("Lexer.x".to_owned(), "Lex".to_owned()),
        ("lexer.x".to_owned(), "Lex".to_owned()),
        ("ld.script".to_owned(), "Linker Script".to_owned()),
        ("Slakefile".to_owned(), "LiveScript".to_owned()),
        (".luacheckrc".to_owned(), "Lua".to_owned()),
        ("configure.ac".to_owned(), "M4Sugar".to_owned()),
        ("BSDmakefile".to_owned(), "Makefile".to_owned()),
        ("GNUmakefile".to_owned(), "Makefile".to_owned()),
        ("Kbuild".to_owned(), "Makefile".to_owned()),
        ("Makefile".to_owned(), "Makefile".to_owned()),
        ("Makefile.am".to_owned(), "Makefile".to_owned()),
        ("Makefile.boot".to_owned(), "Makefile".to_owned()),
        ("Makefile.builder".to_owned(), "Makefile".to_owned()),
        ("Makefile.frag".to_owned(), "Makefile".to_owned()),
        ("Makefile.in".to_owned(), "Makefile".to_owned()),
        ("Makefile.inc".to_owned(), "Makefile".to_owned()),
        ("Makefile.wat".to_owned(), "Makefile".to_owned()),
        ("makefile".to_owned(), "Makefile".to_owned()),
        ("makefile.sco".to_owned(), "Makefile".to_owned()),
        ("mkfile".to_owned(), "Makefile".to_owned()),
        ("contents.lr".to_owned(), "Markdown".to_owned()),
        ("pom.xml".to_owned(), "Maven POM".to_owned()),
        ("meson.build".to_owned(), "Meson".to_owned()),
        ("meson_options.txt".to_owned(), "Meson".to_owned()),
        (
            "descrip.mmk".to_owned(),
            "Module Management System".to_owned()
        ),
        (
            "descrip.mms".to_owned(),
            "Module Management System".to_owned()
        ),
        (".npmrc".to_owned(), "NPM Config".to_owned()),
        ("nextflow.config".to_owned(), "Nextflow".to_owned()),
        ("nginx.conf".to_owned(), "Nginx".to_owned()),
        ("nim.cfg".to_owned(), "Nim".to_owned()),
        ("Nukefile".to_owned(), "Nu".to_owned()),
        (".php".to_owned(), "PHP".to_owned()),
        (".php_cs".to_owned(), "PHP".to_owned()),
        (".php_cs.dist".to_owned(), "PHP".to_owned()),
        ("Phakefile".to_owned(), "PHP".to_owned()),
        ("Makefile.PL".to_owned(), "Perl".to_owned()),
        ("Rexfile".to_owned(), "Perl".to_owned()),
        ("ack".to_owned(), "Perl".to_owned()),
        ("cpanfile".to_owned(), "Perl".to_owned()),
        ("Procfile".to_owned(), "Procfile".to_owned()),
        ("Modulefile".to_owned(), "Puppet".to_owned()),
        (".gclient".to_owned(), "Python".to_owned()),
        ("DEPS".to_owned(), "Python".to_owned()),
        ("SConscript".to_owned(), "Python".to_owned()),
        ("SConstruct".to_owned(), "Python".to_owned()),
        ("Snakefile".to_owned(), "Python".to_owned()),
        ("wscript".to_owned(), "Python".to_owned()),
        ("__init__.py".to_owned(), "Python".to_owned()),
        ("installscript.qs".to_owned(), "Qt Script".to_owned()),
        (
            "toolchain_installscript.qs".to_owned(),
            "Qt Script".to_owned()
        ),
        ("m3makefile".to_owned(), "Quake".to_owned()),
        ("m3overrides".to_owned(), "Quake".to_owned()),
        (".Rprofile".to_owned(), "R".to_owned()),
        ("expr-dist".to_owned(), "R".to_owned()),
        (".inputrc".to_owned(), "Readline Config".to_owned()),
        ("inputrc".to_owned(), "Readline Config".to_owned()),
        (
            "language-subtag-registry.txt".to_owned(),
            "Record Jar".to_owned()
        ),
        ("_redirects".to_owned(), "Redirect Rules".to_owned()),
        ("eqnrc".to_owned(), "Roff".to_owned()),
        ("mmn".to_owned(), "Roff".to_owned()),
        ("mmt".to_owned(), "Roff".to_owned()),
        ("troffrc".to_owned(), "Roff".to_owned()),
        ("troffrc-end".to_owned(), "Roff".to_owned()),
        (".irbrc".to_owned(), "Ruby".to_owned()),
        (".pryrc".to_owned(), "Ruby".to_owned()),
        (".simplecov".to_owned(), "Ruby".to_owned()),
        ("Appraisals".to_owned(), "Ruby".to_owned()),
        ("Berksfile".to_owned(), "Ruby".to_owned()),
        ("Brewfile".to_owned(), "Ruby".to_owned()),
        ("Buildfile".to_owned(), "Ruby".to_owned()),
        ("Capfile".to_owned(), "Ruby".to_owned()),
        ("Dangerfile".to_owned(), "Ruby".to_owned()),
        ("Deliverfile".to_owned(), "Ruby".to_owned()),
        ("Fastfile".to_owned(), "Ruby".to_owned()),
        ("Gemfile".to_owned(), "Ruby".to_owned()),
        ("Guardfile".to_owned(), "Ruby".to_owned()),
        ("Jarfile".to_owned(), "Ruby".to_owned()),
        ("Mavenfile".to_owned(), "Ruby".to_owned()),
        ("Podfile".to_owned(), "Ruby".to_owned()),
        ("Puppetfile".to_owned(), "Ruby".to_owned()),
        ("Rakefile".to_owned(), "Ruby".to_owned()),
        ("Snapfile".to_owned(), "Ruby".to_owned()),
        ("Thorfile".to_owned(), "Ruby".to_owned()),
        ("Vagrantfile".to_owned(), "Ruby".to_owned()),
        ("buildfile".to_owned(), "Ruby".to_owned()),
        ("file_contexts".to_owned(), "SELinux Policy".to_owned()),
        ("genfs_contexts".to_owned(), "SELinux Policy".to_owned()),
        ("initial_sids".to_owned(), "SELinux Policy".to_owned()),
        ("port_contexts".to_owned(), "SELinux Policy".to_owned()),
        ("security_classes".to_owned(), "SELinux Policy".to_owned()),
        ("ssh-config".to_owned(), "SSH Config".to_owned()),
        ("ssh_config".to_owned(), "SSH Config".to_owned()),
        ("sshconfig".to_owned(), "SSH Config".to_owned()),
        ("sshconfig.snip".to_owned(), "SSH Config".to_owned()),
        ("sshd-config".to_owned(), "SSH Config".to_owned()),
        ("sshd_config".to_owned(), "SSH Config".to_owned()),
        (".bash_aliases".to_owned(), "Shell".to_owned()),
        (".bash_history".to_owned(), "Shell".to_owned()),
        (".bash_logout".to_owned(), "Shell".to_owned()),
        (".bash_profile".to_owned(), "Shell".to_owned()),
        (".bashrc".to_owned(), "Shell".to_owned()),
        (".cshrc".to_owned(), "Shell".to_owned()),
        (".env".to_owned(), "Shell".to_owned()),
        (".env.example".to_owned(), "Shell".to_owned()),
        (".flaskenv".to_owned(), "Shell".to_owned()),
        (".kshrc".to_owned(), "Shell".to_owned()),
        (".login".to_owned(), "Shell".to_owned()),
        (".profile".to_owned(), "Shell".to_owned()),
        (".zlogin".to_owned(), "Shell".to_owned()),
        (".zlogout".to_owned(), "Shell".to_owned()),
        (".zprofile".to_owned(), "Shell".to_owned()),
        (".zshenv".to_owned(), "Shell".to_owned()),
        (".zshrc".to_owned(), "Shell".to_owned()),
        ("9fs".to_owned(), "Shell".to_owned()),
        ("PKGBUILD".to_owned(), "Shell".to_owned()),
        ("bash_aliases".to_owned(), "Shell".to_owned()),
        ("bash_logout".to_owned(), "Shell".to_owned()),
        ("bash_profile".to_owned(), "Shell".to_owned()),
        ("bashrc".to_owned(), "Shell".to_owned()),
        ("cshrc".to_owned(), "Shell".to_owned()),
        ("gradlew".to_owned(), "Shell".to_owned()),
        ("kshrc".to_owned(), "Shell".to_owned()),
        ("login".to_owned(), "Shell".to_owned()),
        ("man".to_owned(), "Shell".to_owned()),
        ("profile".to_owned(), "Shell".to_owned()),
        ("zlogin".to_owned(), "Shell".to_owned()),
        ("zlogout".to_owned(), "Shell".to_owned()),
        ("zprofile".to_owned(), "Shell".to_owned()),
        ("zshenv".to_owned(), "Shell".to_owned()),
        ("zshrc".to_owned(), "Shell".to_owned()),
        (".shellcheckrc".to_owned(), "ShellCheck Config".to_owned()),
        ("Singularity".to_owned(), "Singularity".to_owned()),
        ("Android.bp".to_owned(), "Soong".to_owned()),
        ("BUCK".to_owned(), "Starlark".to_owned()),
        ("BUILD".to_owned(), "Starlark".to_owned()),
        ("BUILD.bazel".to_owned(), "Starlark".to_owned()),
        ("Tiltfile".to_owned(), "Starlark".to_owned()),
        ("WORKSPACE".to_owned(), "Starlark".to_owned()),
        ("Cargo.lock".to_owned(), "TOML".to_owned()),
        ("Gopkg.lock".to_owned(), "TOML".to_owned()),
        ("Pipfile".to_owned(), "TOML".to_owned()),
        ("poetry.lock".to_owned(), "TOML".to_owned()),
        ("alire.lock".to_owned(), "TOML".to_owned()),
        ("owh".to_owned(), "Tcl".to_owned()),
        ("starfield".to_owned(), "Tcl".to_owned()),
        ("AUTHORS".to_owned(), "Text".to_owned()),
        ("CITATION".to_owned(), "Text".to_owned()),
        ("CITATIONS".to_owned(), "Text".to_owned()),
        ("CHANGELOG".to_owned(), "Text".to_owned()),
        ("COPYING".to_owned(), "Text".to_owned()),
        ("COPYING.LESSER".to_owned(), "Text".to_owned()),
        ("COPYING.regex".to_owned(), "Text".to_owned()),
        ("COPYRIGHT.regex".to_owned(), "Text".to_owned()),
        ("FONTLOG".to_owned(), "Text".to_owned()),
        ("HACKING".to_owned(), "Text".to_owned()),
        ("INSTALL".to_owned(), "Text".to_owned()),
        ("INSTALL.mysql".to_owned(), "Text".to_owned()),
        ("LICENSE".to_owned(), "Text".to_owned()),
        ("LICENSE-GPL2".to_owned(), "Text".to_owned()),
        ("LICENSE.mysql".to_owned(), "Text".to_owned()),
        ("NEWS".to_owned(), "Text".to_owned()),
        ("README".to_owned(), "Text".to_owned()),
        ("README.me".to_owned(), "Text".to_owned()),
        ("README.mysql".to_owned(), "Text".to_owned()),
        ("README.nss".to_owned(), "Text".to_owned()),
        ("changelog".to_owned(), "Text".to_owned()),
        ("click.me".to_owned(), "Text".to_owned()),
        ("delete.me".to_owned(), "Text".to_owned()),
        ("keep.me".to_owned(), "Text".to_owned()),
        ("package.mask".to_owned(), "Text".to_owned()),
        ("package.use.mask".to_owned(), "Text".to_owned()),
        ("package.use.stable.mask".to_owned(), "Text".to_owned()),
        ("read.me".to_owned(), "Text".to_owned()),
        ("readme.1st".to_owned(), "Text".to_owned()),
        ("readme".to_owned(), "Text".to_owned()),
        ("test.me".to_owned(), "Text".to_owned()),
        ("use.mask".to_owned(), "Text".to_owned()),
        ("use.stable.mask".to_owned(), "Text".to_owned()),
        ("version".to_owned(), "Text".to_owned()),
        (
            ".tm_properties".to_owned(),
            "TextMate Properties".to_owned()
        ),
        (".exrc".to_owned(), "Vim Script".to_owned()),
        (".gvimrc".to_owned(), "Vim Script".to_owned()),
        (".nvimrc".to_owned(), "Vim Script".to_owned()),
        (".vimrc".to_owned(), "Vim Script".to_owned()),
        ("_vimrc".to_owned(), "Vim Script".to_owned()),
        ("gvimrc".to_owned(), "Vim Script".to_owned()),
        ("nvimrc".to_owned(), "Vim Script".to_owned()),
        ("vimrc".to_owned(), "Vim Script".to_owned()),
        (".wgetrc".to_owned(), "Wget Config".to_owned()),
        (
            "encodings.dir".to_owned(),
            "X Font Directory Index".to_owned()
        ),
        (
            "fonts.alias".to_owned(),
            "X Font Directory Index".to_owned()
        ),
        ("fonts.dir".to_owned(), "X Font Directory Index".to_owned()),
        (
            "fonts.scale".to_owned(),
            "X Font Directory Index".to_owned()
        ),
        (".XCompose".to_owned(), "XCompose".to_owned()),
        ("XCompose".to_owned(), "XCompose".to_owned()),
        ("xcompose".to_owned(), "XCompose".to_owned()),
        (".classpath".to_owned(), "XML".to_owned()),
        (".cproject".to_owned(), "XML".to_owned()),
        (".project".to_owned(), "XML".to_owned()),
        ("App.config".to_owned(), "XML".to_owned()),
        ("NuGet.config".to_owned(), "XML".to_owned()),
        ("Settings.StyleCop".to_owned(), "XML".to_owned()),
        ("Web.Debug.config".to_owned(), "XML".to_owned()),
        ("Web.Release.config".to_owned(), "XML".to_owned()),
        ("Web.config".to_owned(), "XML".to_owned()),
        ("packages.config".to_owned(), "XML".to_owned()),
        (".clang-format".to_owned(), "YAML".to_owned()),
        (".clang-tidy".to_owned(), "YAML".to_owned()),
        (".gemrc".to_owned(), "YAML".to_owned()),
        ("CITATION.cff".to_owned(), "YAML".to_owned()),
        ("glide.lock".to_owned(), "YAML".to_owned()),
        ("yarn.lock".to_owned(), "YAML".to_owned()),
        (".curlrc".to_owned(), "cURL Config".to_owned()),
        ("_curlrc".to_owned(), "cURL Config".to_owned()),
        (".dir_colors".to_owned(), "dircolors".to_owned()),
        (".dircolors".to_owned(), "dircolors".to_owned()),
        ("DIR_COLORS".to_owned(), "dircolors".to_owned()),
        ("_dir_colors".to_owned(), "dircolors".to_owned()),
        ("_dircolors".to_owned(), "dircolors".to_owned()),
        ("dir_colors".to_owned(), "dircolors".to_owned()),
        (".nanorc".to_owned(), "nanorc".to_owned()),
        ("nanorc".to_owned(), "nanorc".to_owned()),
        ("robots.txt".to_owned(), "robots.txt".to_owned()),
    ]
    .iter()
    .cloned()
    .collect();
}
